ALTER TABLE "Shipment" ADD COLUMN IF NOT EXISTS "deliveryLat" DOUBLE PRECISION;
ALTER TABLE "Shipment" ADD COLUMN IF NOT EXISTS "deliveryLng" DOUBLE PRECISION;
ALTER TABLE "Shipment" ADD COLUMN IF NOT EXISTS "deliveryNote" VARCHAR(300);
